const data={
    products:[{
        _id:'1',
        price:120,
        name:'nike slim shirts',
        category:'shirts',
        image:'/images/black_1.png',
        countstuck:4,
        rating:4.5,
        numreviews:10,
        description:'high quality product',
    },
    {
        _id:'2',
        price:100,
        name:'puma slim shirts',
        category:'shirts',
        image:'/images/gray_2.png',
        rating:3.5,
        numreviews:8,
        description:'high quality product',
        countstuck:0,
    },
    {
        _id:'3',
        price:80,
        name:'gucci slim shirts',
        category:'shirts',
        image:'/images/yellow_3.png',
        rating:2.5,
        numreviews:15,
        description:'high quality product',
        countstuck:4,
    },
    {
        _id:'4',
        price:90,
        name:'adidas slim shirts',
        category:'shirts',
        image:'/images/black_4.png',
        rating:4.5,
        numreviews:16,
        description:'high quality product',
        countstuck:4,
    },
    {
        _id:'5',
        price:70,
        name:'luisviton slim shirts',
        category:'shirts',
        image:'./images/gray_2.png',
        rating:3.5,
        numreviews:14,
        description:'high quality product',
        countstuck:4,
    },
    {
        _id:'6',
        price:20,
        name:'rebuk slim shirts',
        category:'shirts',
        image:'/images/black_1.png',
        rating:1.5,
        numreviews:13,
        description:'high quality product',
        countstuck:0,
    },],
};
export default data;